---
apiVersion: v1
kind: ConfigMap
metadata:
  name: connection-details
data:
  DB_HOST: redis:6379
  RABBIT_HOST: rabbitmq:5672
  OTEL_EXPORTER_OTLP_ENDPOINT: otel-collector:4317
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.8-management
        ports:
        - containerPort: 5672
        - containerPort: 15672
        readinessProbe:
          tcpSocket:
            port: 5672
          initialDelaySeconds: 10
          periodSeconds: 10
      - name: exporter
        image: kbudde/rabbitmq-exporter:latest
        ports:
        - containerPort: 9419
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  ports:
  - port: 5672
    protocol: TCP
    name: amqp
  - port: 15672
    protocol: TCP
    name: management
  - port: 9419
    protocol: TCP
    name: metrics
  selector:
    app: rabbitmq
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
        readinessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 10
          periodSeconds: 10
      - name: exporter
        image: oliver006/redis_exporter:latest
        ports:
        - containerPort: 9121
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  ports:
  - port: 6379
    protocol: TCP
    name: redis
  - port: 9121
    protocol: TCP
    name: metrics
  selector:
    app: redis
